#!/usr/bin/env python3

import re
import subprocess
import sys

from pathlib import Path

CONFIG_NAME = '.fancyconfig'
CONFIG_PATHS = [path for path
                in [Path.home() / CONFIG_NAME,
                    Path(CONFIG_NAME)]
                if path.is_file()]


def get_emoji(code: str) -> str:
    for config_path in CONFIG_PATHS:
        try:
            return run_git_config(config_path, f'emoji.{code}')
        except subprocess.CalledProcessError:
            continue

    raise RuntimeError(f"could not retrieve emoji for :{code}:")


def run_git_config(config_path: Path, name: str) -> str:
    args = ('git', 'config', '-f', config_path, name)

    return subprocess.run(args, stdout=subprocess.PIPE, check=True,
                          encoding='utf-8').stdout[:-1]  # drops trailing "\n"


def replace_emoji_sequences(text: str) -> str:
    return re.sub(r':(?P<code>[a-zA-Z0-9_+-]+):',
                  lambda match: get_emoji(match.group('code')),
                  text)


with open(sys.argv[1], 'r+') as message_file:
    message = message_file.read()
    message_file.seek(0)
    message_file.write(replace_emoji_sequences(message))
    message_file.truncate()
