#!/usr/bin/env python3

import re
import subprocess
import sys


def get_emoji(code: str) -> str:
    args = ['git', 'config', '-f', '.fancyconfig', f'emoji.{code}']

    return subprocess.run(args, stdout=subprocess.PIPE, check=True,
                          encoding='utf-8').stdout[:-1]  # drops trailing "\n"


def replace_codes(text: str) -> str:
    return re.sub(r':(?P<code>[a-zA-Z0-9_+-]+):',
                  lambda match: get_emoji(match.group('code')),
                  text)


with open(sys.argv[1], 'r+') as message_file:
    message = message_file.read()
    message_file.seek(0)
    message_file.write(replace_codes(message))
    message_file.truncate()
